name: Backend service deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: '12.13.0'
  AWS_REGION: us-east-2

jobs:
  build:
    name: Build, test and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout project repository
        uses: actions/checkout@v2

      - name: Setup CDK and deploy project
        working-directory: ./cdk
        run: |
          export STACK_NAME=SoundCarStackProd-$(echo "${GITHUB_REF#refs/heads/}" | sed -r "s/[^-a-zA-Z0-9]+/-/g")
          npm install
          npm run cdk bootstrap
          npm run cdk synth
          npm run cdk deploy -- --require-approval=never
          npm run generate-config -- "${STACK_NAME}" "${STACK_REGION}" ../ui/src/autoGenConfig.js
        env:
          STACK_REGION: ${{ env.AWS_REGION }}
          VERIFIED_MAIL: registration@carcloud.com
          VERIFIED_MAIL_REGION: ${{ env.AWS_REGION }}

      - name: Build website and deploy
        working-directory: ./ui
        run: |
          export BUCKET_NAME=$(node --print "require('./src/autoGenConfig.js').uiBucketName")
          npm install
          npm run build
          aws s3 sync --delete ./dist/ "s3://${BUCKET_NAME}"

