name: Backend service deployment pipeline

on:
  push:
    branches:
      - master
    paths:
      - service/**
      - .github/workflows/**

  pull_request:
    paths:
      - service/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Setup go dep
        run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Checkout full repository
        uses: actions/checkout@v2

      - name: Make build of the Service project
        working-directory: ./service
        run: |
          make build

      - name: Deploy with Serverless
        uses: serverless/github-action@master
        with:
          path: ./service
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

